const wordList = [
    ["France", "Angleterre", "Suisse", "Belgique", "Espagne"],
    ["Amazon", "Google", "Facebook", "Linkedin", "Twitter", "Youtube"],
    ["New-York", "Los Angeles", "Washington", "Miami"],
    ["mangue", "goyave", "pomme", "kiwi", "cerise", "fraise", "citron"],
    ["Vladimir Putin", "Emanuel Macron", "Donald Trump", "Kim Jung Un"],
    ["Che Guevara", "Fidel Castro", "Lénine", "Karl Marx"],
    ["Guerre du Vietnam", "1ère Guerre Mondiale", "2ème Guerre Mondiale", "Révolution Française"],
    ["Counter Strike", "Valorant", "Fortnite", "Overwatch"],
    ["Orc", "Elfe", "Nain", "Draenei", "Gnome"],
    ["Sylvanas", "Anduin Wrynn", "Hurlevent", "Thrall", "Le Roi Liche"],
    ["Domingo", "Zerator", "Sardoche", "Squeezie"],
    ["Rambo", "Rocky", "Bruce Willis", "Sylverster Stallone"],
    ["Katarina", "Miss Fortune", "Morgana", "Tomb Raider"],
    ["Superman", "Batman", "Spider-Man", "le Joker", "Thanos", "Iron Man"],
    ["Games Of Throne", "X-Files", "The Walking Dead", "La casa de papel"],
    ["Harry Potter", "Hermione Granger", "Ron Weasley", "Drago Malefoy", "Dumbledore"],
    ["Aladdin", "Robin des Bois", "Peter Pan", "Pinocchio"],
    ["Dingo", "Donald", "Mickey Mouse", "Minnie", "Picsou", "Donald"],
    ["Noël", "anniversaire", "Saint Valentin"],
    ["football", "basketball", "baseball", "handball"],
    ["Hercule Poirot", "Miss Marple", "Sherlock Holmes", "Dr Watson", "Arsène Lupin"],
    ["Playstation", "Nintendo", "Xbox"],
    ["Windows", "Macintosh", "Linux"],
    ["Harry Potter (le Film)", "Le seigneur des anneaux", "Star Wars"],
    ["Triss", "Yennefer", "Geralt", "Dovakhin"],
    ["Zelda", "Link", "Ganon", "Peach", "Mario", "Luigi", "Wario"],
    ["Aragorn (Seigneur des Anneaux)", "Sam Gamegie (Seigneur des Anneaux)", "Frodon (Seigneur des Anneaux)", "Saroumane (Seigneur des Anneaux)", "Gandalf (Seigneur des Anneaux)"],
    ["Dark Vador", "Luke Skywalker", "Han Solo", "Yoda", "Anakin Skywalker"],
    ["James Bond", "OSS 117", "Jason Bourne", "Indiana Jones", "Han Solo", "Capitaine Jack Sparrow"],
    ["Rolling Stone", "ACDC", "Beatles", "Guns N' Roses", "Led Zeppelin", "The Who"],
    ["Kill bill", "Jango Unchained", "Pulp Fiction", "Sin City"],
    ["Quentin Tarantino", "Steven Spielberg", "Martin Scorsese", "Christopher Nolan"],
    ["Samsung", "Apple", "Nokia", "Huawei"],
    ["Zizi", "Chatte", "Seins", "Torse", "Tibia", "Fesses"],
    ["Pizza", "Pattes", "Spaghettis", "Mozarella"],
    ["Facebook", "Twitter", "Instagram", "TikTok"],
    ["Deezer", "Spotify", "Youtube", "Vimeo", "Dailymotion"],
    ["€ (euro)", "$ (dollar)", "£ (livre)", "¥ (monnaie le Yen)"],
    ["Feu", "Eau", "Terre", "Vent"],
    ["Univers", "Galaxie", "Planètes", "Système", "Alien"],
    ["Milf", "Inter-racial", "Hentai", "Sexe", "Porn-Star"],
    ["Casserole", "Poêle", "Cocotte Minute", "Four", "Assiette", "Fourchette", "Couteau", "Tasse", "Verre"],
    ["Lancer de Javelot", "Lancer de Poids", "Lancer de disque", "Sprint"],
    ["Arts-Plastiques", "Sciences", "Mathématiques", "Biologie"],
    ["Salamèche", "Pikachu", "Bulbizarre", "Carapuce", "Evoli", "Miaouss"],
    ["David Bowie", "Mick Jagger", "Iggy Pop", "John Lennon", "Led Zeppelin", "Céline Dion", "Mickaell Jackson", "Madonna"],
    ["Les Nuls", "Les Inconnus", "Les Robins Des Bois", "Les Bronzés", "Palmashow"],
    ["Pocahontas", "Belle (et la Bête)", "Aurore (La Belle au Bois Dormant)", "Jasmine", "Ariel (La Petite Sirène)", "Nala (Roi Lion)", "Blanche-Neige", "Mulan", "Cendrillon"],
    ["Boulanger", "Plombier", "Médecin", "Avocat", "Architecte"],
    ["Harmonica", "Flûte", "Violon", "Guitare", "Piano"],
    ["Napoléon", "Jules César", "Adolf Hilter", "Charlie Chaplin"],
    ["Jambe", "Main", "Doigt", "Langue", "Pied", "Tibia", "Mollet"],
    ["Ane", "Cheval", "Chien", "Chat", "Singe", "Chimpanzé", "Dauphin", "Baleine", "Requin", "Souris", "Lapin"],
    ["Rateau", "Pelle", "Balai", "Marteau", "Tournevis", "Scie"],

    //["mot","mot","mot","mot"],
];

export default wordList;