const wordList = [
    {word1: "mer", word2: "fleuve"},
    {word1: "moto", word2: "voiture"},
    {word1: "France", word2: "Angleterre"},
    {word1: "Océan", word2: "Mer"},
    {word1: "Chat", word2: "Tigre"},
    {word1: "Microsoft Office", word2: "Open Office"},
    {word1: "Google Chrome", word2: "Firefox"},
    {word1: "Amazon", word2: "Alibaba"},
    {word1: "Calendrier", word2: "Agenda"},
    {word1: "Archives", word2: "Bibliothèque"},
    {word1: "Jardin", word2: "Parc"},
    {word1: "Séoul", word2: "Tokyo"},
    {word1: "New-York", word2: "Los Angeles"},
    {word1: "Diesel", word2: "Essence"},
    {word1: "Noix de pécan", word2: "Noix de cajou"},
    {word1: "Mangue", word2: "Goyave"},
    {word1: "Martinique", word2: "Guadeloupe"},
    {word1: "Che Guevara", word2: "Fidel Castro"},
    {word1: "1ère Guerre Mondiale", word2: "2nde Guerre Mondiale"},
    {word1: "CS GO", word2: "Valorant"},
    {word1: "Wow", word2: "FFXIV"},
    {word1: "Horde", word2: "Sylvanas"},
    {word1: "Mûre", word2: "Cassis"},
    {word1: "Mercure", word2: "Vénus"},
    {word1: "Carrefour", word2: "Leclerc"},
    {word1: "Evian", word2: "Volvic"},
    {word1: "Chèvre", word2: "Brebis"},
    {word1: "Phacochère", word2: "Sanglier"},
    {word1: "Dromadaire", word2: "Chameau"},
    {word1: "Pingouin", word2: "Manchot"},
    {word1: "Hiroshima", word2: "Fukushima"},
    {word1: "Mousse au chocolat", word2: "Crème au chocolat"},
    {word1: "Burger King", word2: "Mac Do"},
    {word1: "Bavette", word2: "Steack"},
    {word1: "Théière", word2: "Thé"},
    {word1: "Outreterre", word2: "Draenor"},
    {word1: "Nains", word2: "Nains sombrefer"},
    {word1: "Goulet Chanteguerre", word2: "Arathi"},
    {word1: "Combats pokemons", word2: "Combats mascottes"},
    {word1: "Netflix", word2: "Amazon Video"},
    {word1: "LOL", word2: "DOTA"},
    {word1: "Mickey", word2: "Minnie"},
    {word1: "Lunettes de vue", word2: "Lunettes de soleil"},
    {word1: "Moustache", word2: "Barbe"},
    {word1: "Oreiller", word2: "Lit"},
    {word1: "Flan", word2: "Far breton"},
    {word1: "Hercule Poirot", word2: "Miss Marple"},
    {word1: "Columbo", word2: "Navarro"},
    {word1: "La Loire", word2: "Le Maine"},
    {word1: "Sardine", word2: "Maquereau"},
    {word1: "Buffle", word2: "Taureau"},
    {word1: "Guépard", word2: "Panthère"},
    {word1: "Triangle", word2: "Pyramide"},
    {word1: "Bic", word2: "Feutre"},
    {word1: "Atlantique", word2: "Pacifique"},
    {word1: "Marvel", word2: "DC Comics"},
    {word1: "Disney", word2: "Pixar"},
    {word1: "Pictionary", word2: "Skribbl.io"},
    {word1: "Lapi", word2: "Oono"},
    {word1: "Hôpital", word2: "Clinique"},
    {word1: "Assemblée Nationale", word2: "Sénat"},
    {word1: "Pomme", word2: "Poire"},
];

export default wordList;